services:
  - type: web
    name: fuel-station-api
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && gunicorn wsgi:app"
    envVars:
      - key: PYTHONUNBUFFERED
        value: true
      - key: FLASK_ENV
        value: production
