services:
  - type: web
    name: fuel-station-api
    env: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "gunicorn --chdir backend --workers 1 --bind 0.0.0.0:5000 wsgi:app"
    envVars:
      - key: PYTHONUNBUFFERED
        value: true
      - key: FLASK_ENV
        value: production
